/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

fun toElves(input: String): MutableList<MutableList<Int>> =
    input.lines().fold(mutableListOf(mutableListOf())) { acc, str ->
        when (str.trim().length) {
            0 ->  acc.add( mutableListOf())
            else -> acc.last().add(str.toInt())
        }
        acc
    }

fun calcMostCalories(input: String): Int = toElves(input).maxOf { it.sum() }

fun top3(input: String): Int = toElves(input)
    .map { it.sum() }
    .sortedBy { it }
    .takeLast(3)
    .sum()

